- name: install-python3
  package:
    name: python3-pip
    state: present

- name: Install kubernetes
  ansible.builtin.pip:
    name: kubernetes

- name: Copy yaml files
  ansible.builtin.copy:
    src: 
      - namespace.yaml
      - ServiceAccount.yaml
      - deployment.yaml
      - service.yaml
    dest: '/home/ubuntu/k8s'

- name: Create resources
  remote_user: ubuntu
  become: false
  kubernetes.core.k8s:
    state: present
    src:
      - namespace.yaml
      - ServiceAccount.yaml
      - deployment.yaml
      - service.yaml
